services: 
    backend:
        container_name: backend
        restart: always
        build: 
            context: ./
            dockerfile: WebApplication2/Dockerfile
        environment:
            DB_CONNECTION: "Server=mysql;Database=root;Uid=root;Pwd=root;"
        ports:
            - 443:443
            - 80:80 
        expose:
            - 443
            - 80
        depends_on:
            - mysql

    mysql:
        container_name: mysql
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
            - 3306:3306 
        expose:
            - 3306 
